name: Check Android compatibility

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    name: Run Android Compatibility Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-22
          accept-android-sdk-licenses: 'true'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Tests
        run: |
          ./gradlew test \
          --stacktrace
